/**
 * relay Design System — MCP shared handlers (transport-agnostic).
 *
 *   The tool definitions, formatting, and dispatch logic live here so both
 *   transports reuse exactly the same behaviour:
 *     - src/mcp/server.mjs  → stdio (local, bundled to dist/mcp.mjs via esbuild)
 *     - src/mcp/worker.mjs  → Streamable HTTP on Cloudflare Workers (remote)
 *
 *   Data comes from dist/mcp-index.json (generated by scripts/build-mcp.mjs).
 *   Each transport's bundler (esbuild / wrangler) inlines this JSON import.
 *
 *   Tools:
 *     list_components          — every component with name / 和名 / summary / classes
 *     get_component(name)      — full spec: props, states, colors, usage, classes, snippet
 *     get_tokens(category?)    — colors / typography / spacing / radius / shadow
 *     get_design_principles    — non-negotiable rules + forbidden patterns (Top 10)
 *     search(query)            — fuzzy search across components / tokens / principles
 */

import index from "../../dist/mcp-index.json" with { type: "json" };

export { index };
export const SERVER_INFO = { name: "relay-design-system", version: index.version };
export const TOKEN_CATEGORIES = Object.keys(index.tokens); // colors, typography, spacing, radius, shadow

/* ------------------------------------------------------------------ helpers */

function figmaUrl(node) {
  if (!node) return null;
  return `https://www.figma.com/design/${index.figmaFile}/relay-Design-System?node-id=${node.replace(/:/g, "-")}`;
}

function findComponent(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return null;
  const byName = index.components.find((c) => c.name === q);
  if (byName) return byName;
  return (
    index.components.find((c) => c.name.includes(q) || q.includes(c.name)) ||
    index.components.find((c) => c.nameJa && c.nameJa.toLowerCase() === q) ||
    index.components.find((c) => c.classes.includes(q)) ||
    null
  );
}

function formatComponentList() {
  const lines = [
    `# relay Design System — ${index.components.length} components (v${index.version})`,
    "",
    `各コンポーネントの完全仕様は get_component("<name>") を呼んでください（props / 状態 / 色 / usage / クラス / snippet）。`,
    `UI を書く前に get_design_principles で必須ルールと禁止パターンを確認することを推奨します。`,
    "",
  ];
  for (const c of index.components) {
    const ja = c.nameJa ? `（${c.nameJa}）` : "";
    const summary = c.summary ? ` — ${c.summary}` : "";
    const cls = c.classes.slice(0, 6).join(", ");
    lines.push(`- **${c.name}**${ja}${summary}`);
    lines.push(`  classes: ${cls}${c.classes.length > 6 ? ", …" : ""}`);
  }
  return lines.join("\n");
}

function formatComponent(c) {
  const ja = c.nameJa ? ` （${c.nameJa}）` : "";
  const out = [`# ${c.name}${ja}`];
  const url = figmaUrl(c.figmaNode);
  if (url) out.push(`Figma: component set ${c.figmaNode} — ${url}`);
  out.push("");
  out.push(`## 仕様（src/components/${c.name}.css ヘッダより）`, "", c.doc || "（ドキュメントコメントなし）", "");
  out.push(`## CSS クラス（${c.classes.length}）`, "", c.classes.map((x) => `.${x}`).join(", "), "");
  out.push("## コピペ用 HTML スニペット", "");
  out.push(c.snippet ? "```html\n" + c.snippet + "\n```" : "（このコンポーネントの snippet はありません。上記の Usage と CSS クラスを参照）");
  return out.join("\n");
}

function formatTokens(category) {
  const cats = category ? [category] : TOKEN_CATEGORIES;
  const out = [`# relay Design System — design tokens (v${index.version})`, ""];
  out.push(
    "値は解決済みの実値（例: --color-primary-500 = #30b686）。CSS が無い環境（スタンドアロン生成）でも、この実値をそのまま使うこと。",
    "Tailwind ユーティリティ名は --color-x-500 → bg-x-500、--spacing*N → p-N 等に対応。",
    "",
  );
  for (const cat of cats) {
    const entries = index.tokens[cat];
    if (!entries) continue;
    out.push(`## ${cat} (${entries.length})`, "");
    for (const t of entries) out.push(`- \`${t.name}\`: ${t.value}${t.via ? ` (= ${t.via})` : ""}`);
    out.push("");
  }
  return out.join("\n");
}

/** Resolved value of a color token by name (e.g. "--color-primary-500" → "#30b686"). */
function colorValue(name) {
  const t = (index.tokens.colors || []).find((c) => c.name === name);
  return t ? t.value : "?";
}

function formatBrandColors() {
  return [
    "## ブランド基調色（実値・これを使う）",
    "",
    "relay の CSS を読み込まない環境（claude.ai 等のスタンドアロン生成）では、下記の実値を直接使うこと。**青などの独自色は使わない。**",
    "",
    `- primary（ブランド緑）: \`bg-primary-500\` = ${colorValue("--color-primary-500")} / hover \`bg-primary-600\` = ${colorValue("--color-primary-600")} / 濃 \`primary-700\` = ${colorValue("--color-primary-700")}`,
    `- secondary（ブランド黄）: \`secondary-500\` = ${colorValue("--color-secondary-500")}`,
    `- 本文テキスト: \`text-fg-high\` = ${colorValue("--color-fg-high")} / \`text-fg-middle\` = ${colorValue("--color-fg-middle")} / \`text-fg-low\` = ${colorValue("--color-fg-low")}`,
    `- ステータス: success ${colorValue("--color-success-500")} / warning ${colorValue("--color-warning-500")} / negative ${colorValue("--color-negative-500")} / info ${colorValue("--color-info-500")}`,
    `- 背景/境界: page ${colorValue("--color-page")} / border \`stroke-middle\` ${colorValue("--color-stroke-middle")}`,
    "",
    "> 全トークン（余白/角丸/影/タイポ含む実値）は get_tokens を呼ぶこと。",
  ].join("\n");
}

function formatPrinciples() {
  return [
    "# relay Design System — 必須ルール & 禁止パターン",
    "",
    "AI が relay UI を生成する際、以下を必ず守ること。",
    "",
    formatBrandColors(),
    "",
    index.principles || "(principles 未取得)",
    "",
    index.forbiddenPatterns || "(forbidden patterns 未取得)",
  ].join("\n");
}

function runSearch(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return "検索クエリが空です。";

  const compHits = index.components
    .filter(
      (c) =>
        c.name.includes(q) ||
        (c.nameJa && c.nameJa.toLowerCase().includes(q)) ||
        (c.summary && c.summary.toLowerCase().includes(q)) ||
        c.classes.some((cl) => cl.includes(q)) ||
        (c.doc && c.doc.toLowerCase().includes(q)),
    )
    .slice(0, 10);

  const tokenHits = [];
  for (const [cat, entries] of Object.entries(index.tokens)) {
    for (const t of entries) {
      if (t.name.toLowerCase().includes(q) || t.value.toLowerCase().includes(q)) {
        tokenHits.push({ cat, ...t });
      }
    }
  }

  const out = [`# 検索結果: "${query}"`, ""];
  if (compHits.length) {
    out.push("## コンポーネント（get_component で詳細）", "");
    for (const c of compHits) {
      out.push(`- **${c.name}**${c.nameJa ? `（${c.nameJa}）` : ""} → get_component("${c.name}")`);
    }
    out.push("");
  }
  if (tokenHits.length) {
    out.push(`## トークン（get_tokens でカテゴリ全件）`, "");
    for (const t of tokenHits.slice(0, 20)) out.push(`- [${t.cat}] \`${t.name}\`: ${t.value}`);
    if (tokenHits.length > 20) out.push(`- … 他 ${tokenHits.length - 20} 件`);
    out.push("");
  }
  if (!compHits.length && !tokenHits.length) {
    out.push("ヒットなし。list_components / get_tokens / get_design_principles を試してください。");
  }
  return out.join("\n");
}

/* --------------------------------------------------------------------- tools */

export const TOOLS = [
  {
    name: "list_components",
    description:
      "relay Design System の全コンポーネント一覧（英名 / 和名 / 概要 / 主要クラス）を返す。UI を組む前の全体把握に使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_component",
    description:
      "指定コンポーネントの完全仕様（props・状態・色マッピング・usage 例・CSS クラス一覧・コピペ用 HTML スニペット・Figma リンク）を返す。name は 'button' / 'input' など（英名）。",
    inputSchema: {
      type: "object",
      properties: { name: { type: "string", description: "コンポーネント英名（例: button, input, alert, card）" } },
      required: ["name"],
      additionalProperties: false,
    },
  },
  {
    name: "get_tokens",
    description:
      "デザイントークンを返す。category 省略時は全カテゴリ。色・余白・タイポ・角丸・影をハードコードせずトークン経由で書くために使う。",
    inputSchema: {
      type: "object",
      properties: {
        category: { type: "string", enum: TOKEN_CATEGORIES, description: "トークンカテゴリ。省略で全件" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_design_principles",
    description:
      "relay の Non-Negotiable Principles（ハードコード禁止・semantic color・blessed spacing・typo セマンティック層・ARIA 状態 等）と禁止パターン Top 10 を返す。コード生成前のガードに使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "search",
    description:
      "コンポーネント / トークン / 規約を横断であいまい検索し、次に呼ぶべきツールを示す。例: 'ボタン', 'primary', '余白', 'shadow'。",
    inputSchema: {
      type: "object",
      properties: { query: { type: "string", description: "検索キーワード（日本語可）" } },
      required: ["query"],
      additionalProperties: false,
    },
  },
];

/**
 * Run a tool. Returns { text, isError? } — transports wrap this into their own
 * content envelope.
 */
export function callTool(name, args = {}) {
  switch (name) {
    case "list_components":
      return { text: formatComponentList() };
    case "get_component": {
      const c = findComponent(args.name);
      if (!c) {
        return {
          text: `コンポーネント "${args.name}" が見つかりません。\n利用可能: ${index.components
            .map((x) => x.name)
            .join(", ")}`,
        };
      }
      return { text: formatComponent(c) };
    }
    case "get_tokens": {
      if (args.category && !TOKEN_CATEGORIES.includes(args.category)) {
        return { text: `不明な category "${args.category}"。利用可能: ${TOKEN_CATEGORIES.join(", ")}` };
      }
      return { text: formatTokens(args.category) };
    }
    case "get_design_principles":
      return { text: formatPrinciples() };
    case "search":
      return { text: runSearch(args.query) };
    default:
      return { text: `Unknown tool: ${name}`, isError: true };
  }
}

/* ----------------------------------------------------------------- resources */

export function listResources() {
  return [
    {
      uri: "relay://design-constitution",
      name: "relay Design Constitution (DESIGN.md)",
      description: "思想・非交渉原則・クイックリファレンス・禁止パターンの 1 枚憲法",
      mimeType: "text/markdown",
    },
    ...index.components.map((c) => ({
      uri: `relay://component/${c.name}`,
      name: `Component: ${c.name}${c.nameJa ? `（${c.nameJa}）` : ""}`,
      description: c.summary || `relay ${c.name} component spec`,
      mimeType: "text/markdown",
    })),
  ];
}

/** Read a resource by uri → content object. Throws on unknown uri. */
export function readResource(uri) {
  if (uri === "relay://design-constitution") {
    return { uri, mimeType: "text/markdown", text: index.designConstitution };
  }
  const m = uri.match(/^relay:\/\/component\/(.+)$/);
  if (m) {
    const c = index.components.find((x) => x.name === m[1]);
    if (c) return { uri, mimeType: "text/markdown", text: formatComponent(c) };
  }
  throw new Error(`Unknown resource: ${uri}`);
}
