/**
 * relay Design System — MCP shared handlers (transport-agnostic).
 *
 *   The tool definitions, formatting, and dispatch logic live here so both
 *   transports reuse exactly the same behaviour:
 *     - src/mcp/server.mjs  → stdio (local, bundled to dist/mcp.mjs via esbuild)
 *     - src/mcp/worker.mjs  → Streamable HTTP on Cloudflare Workers (remote)
 *
 *   Data comes from dist/mcp-index.json (generated by scripts/build-mcp.mjs).
 *   Each transport's bundler (esbuild / wrangler) inlines this JSON import.
 *
 *   Tools:
 *     get_setup                — CSS 導入手順（UI 着手前に最初に呼ぶ）
 *     list_components          — every component with name / 和名 / summary / classes
 *     get_component(name)      — full spec: props, states, colors, usage, classes, snippet
 *     get_tokens(category?)    — colors / typography / spacing / radius / shadow
 *     get_design_principles    — non-negotiable rules + forbidden patterns (Top 10)
 *     list_assets              — brand assets (logo / illustrations) with直リンク URL
 *     search(query)            — fuzzy search across components / tokens / principles
 */

import index from "../../dist/mcp-index.json" with { type: "json" };

export { index };
export const SERVER_INFO = { name: "relay-design-system", version: index.version };
export const TOKEN_CATEGORIES = Object.keys(index.tokens); // colors, typography, spacing, radius, shadow

/**
 * Standing guidance returned in the `initialize` result. MCP clients load this
 * as system context at connect time, so — unlike a tool the agent must choose to
 * call — these rules stay in effect through a whole implementation session. This
 * targets the common failure mode where an agent connects, calls a tool once,
 * then drifts back to hardcoded values mid-build.
 */
export const INSTRUCTIONS = [
  "relay Design System の MCP。relay 系プロダクトの UI を作るときは必ずこのサーバーの情報を使い、自前のデザインや独自色で実装しないこと。",
  "",
  "【最初に必ず get_setup を呼ぶ】",
  "UI 作業を始める前に、まず get_setup を呼んで CSS の導入手順と確認方法を取得すること。",
  "relay のコンポーネントクラス（.btn / .card / .input 等）は npm パッケージ @light-right/design-system の CSS が読み込まれて初めて効く。MCP はクラス名やトークンの「知識」を渡すだけで CSS 実体は渡さない。CSS 未導入のまま relay クラスを書いても見た目が変わらず、ハードコードに逃げる結果になる。",
  "プロジェクトに未導入なら、UI を書く前に導入を済ませる（手順は get_setup 参照）。",
  "",
  "【実装フロー】",
  "0. get_setup を呼び、CSS が導入済みか確認する（未導入なら導入してから UI を書く）。",
  "1. get_design_principles で必須ルールと禁止パターンを、list_components でコンポーネントの全体像を把握する。",
  "2. 使うコンポーネントごとに get_component(\"<name>\") を呼び、返ってくるコピペ用 HTML スニペットとクラスを土台にする（自分で markup をゼロから組まない）。機能（用途）と使用法の NG を必ず確認し、用途が合わないコンポーネントを流用しない（例: 遷移に button を使わない）。",
  "3. 色・余白・タイポ・角丸・影の具体値が要るときは get_tokens を呼び、解決済みの実値またはトークン名を使う。",
  "4. ロゴ・イラストは list_assets の直リンク URL を使う（独自に作らない）。",
  "",
  "【ハード制約】",
  "- 色 / 余白 / タイポ / 角丸 / 影をハードコードしない（#hex やピクセル直書き・任意値クラスを避け、トークン／ユーティリティ経由で書く）。",
  "- 既存コンポーネントがある UI は手書きで再実装せず relay コンポーネントを使う。",
  "- 独自のブランド色（青など）を持ち込まない。基調はブランド緑 primary / 黄 secondary。",
].join("\n");

/* ------------------------------------------------------------------ helpers */

function figmaUrl(node) {
  if (!node) return null;
  return `https://www.figma.com/design/${index.figmaFile}/relay-Design-System?node-id=${node.replace(/:/g, "-")}`;
}

function findComponent(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return null;
  const byName = index.components.find((c) => c.name === q);
  if (byName) return byName;
  return (
    index.components.find((c) => c.name.includes(q) || q.includes(c.name)) ||
    index.components.find((c) => c.nameJa && c.nameJa.toLowerCase() === q) ||
    index.components.find((c) => c.classes.includes(q)) ||
    null
  );
}

function formatComponentList() {
  const lines = [
    `# relay Design System — ${index.components.length} components (v${index.version})`,
    "",
    `各コンポーネントの完全仕様は get_component("<name>") を呼んでください（props / 状態 / 色 / usage / クラス / snippet）。`,
    `UI を書く前に get_design_principles で必須ルールと禁止パターンを確認することを推奨します。`,
    "",
  ];
  for (const c of index.components) {
    const ja = c.nameJa ? `（${c.nameJa}）` : "";
    // 機能の 1 行目があればそれを概要に使う（用途が伝わる）。無ければ従来の summary。
    const lead = c.function ? c.function.split("\n")[0].trim() : c.summary;
    const summary = lead ? ` — ${lead}` : "";
    const cls = c.classes.slice(0, 6).join(", ");
    lines.push(`- **${c.name}**${ja}${summary}`);
    lines.push(`  classes: ${cls}${c.classes.length > 6 ? ", …" : ""}`);
  }
  return lines.join("\n");
}

/** Remove the column-0 `<label>:` lines and their indented bodies from a header doc. */
function stripDocLabels(doc, labels) {
  const out = [];
  let skipping = false;
  for (const line of doc.split("\n")) {
    const trimmed = line.trim();
    if (labels.some((l) => trimmed === `${l}:`)) { skipping = true; continue; }
    if (skipping) {
      if (trimmed === "") continue; // blank line inside/after the block
      if (/^\s/.test(line)) continue; // indented body → still in the block
      skipping = false; // hit the next column-0 label → block ended
    }
    out.push(line);
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

function formatComponent(c) {
  const ja = c.nameJa ? ` （${c.nameJa}）` : "";
  const out = [`# ${c.name}${ja}`];
  const url = figmaUrl(c.figmaNode);
  if (url) out.push(`Figma: component set ${c.figmaNode} — ${url}`);
  out.push("");

  // 機能 / 使用法 を最初に出す（クラスや snippet を掴む前に「用途と NG」を読ませる）。
  if (c.function) out.push("## 機能", "", c.function, "");
  if (c.usage && ((c.usage.ok && c.usage.ok.length) || (c.usage.ng && c.usage.ng.length))) {
    out.push("## 使用法", "");
    for (const ok of c.usage.ok || []) out.push(`- ✅ ${ok}`);
    for (const ng of c.usage.ng || []) out.push(`- ❌ ${ng}`);
    out.push("");
  }

  // 仕様（doc）からは 機能/使用法 ブロックを除いて重複表示を避ける（doc 全文は index に保持）。
  const spec = c.doc ? stripDocLabels(c.doc, ["機能", "使用法"]) : "";
  out.push(`## 仕様（src/components/${c.name}.css ヘッダより）`, "", spec || "（ドキュメントコメントなし）", "");
  out.push(`## CSS クラス（${c.classes.length}）`, "", c.classes.map((x) => `.${x}`).join(", "), "");
  out.push("## コピペ用 HTML スニペット", "");
  out.push(c.snippet ? "```html\n" + c.snippet + "\n```" : "（このコンポーネントの snippet はありません。上記の Usage と CSS クラスを参照）");
  return out.join("\n");
}

function formatTokens(category) {
  const cats = category ? [category] : TOKEN_CATEGORIES;
  const out = [`# relay Design System — design tokens (v${index.version})`, ""];
  out.push(
    "値は解決済みの実値（例: --color-primary-500 = #30b686）。CSS が無い環境（スタンドアロン生成）でも、この実値をそのまま使うこと。",
    "Tailwind ユーティリティ名は --color-x-500 → bg-x-500、--spacing*N → p-N 等に対応。",
    "",
  );
  for (const cat of cats) {
    const entries = index.tokens[cat];
    if (!entries) continue;
    out.push(`## ${cat} (${entries.length})`, "");
    for (const t of entries) out.push(`- \`${t.name}\`: ${t.value}${t.via ? ` (= ${t.via})` : ""}`);
    out.push("");
  }
  return out.join("\n");
}

/** Resolved value of a color token by name (e.g. "--color-primary-500" → "#30b686"). */
function colorValue(name) {
  const t = (index.tokens.colors || []).find((c) => c.name === name);
  return t ? t.value : "?";
}

function formatBrandColors() {
  return [
    "## ブランド基調色（実値・これを使う）",
    "",
    "relay の CSS を読み込まない環境（claude.ai 等のスタンドアロン生成）では、下記の実値を直接使うこと。**青などの独自色は使わない。**",
    "",
    `- primary（ブランド緑）: \`bg-primary-500\` = ${colorValue("--color-primary-500")} / hover \`bg-primary-600\` = ${colorValue("--color-primary-600")} / 濃 \`primary-700\` = ${colorValue("--color-primary-700")}`,
    `- secondary（ブランド黄）: \`secondary-500\` = ${colorValue("--color-secondary-500")}`,
    `- 本文テキスト: \`text-fg-high\` = ${colorValue("--color-fg-high")} / \`text-fg-middle\` = ${colorValue("--color-fg-middle")} / \`text-fg-low\` = ${colorValue("--color-fg-low")}`,
    `- ステータス: success ${colorValue("--color-success-500")} / warning ${colorValue("--color-warning-500")} / negative ${colorValue("--color-negative-500")} / info ${colorValue("--color-info-500")}`,
    `- 背景/境界: page ${colorValue("--color-page")} / border \`stroke-middle\` ${colorValue("--color-stroke-middle")}`,
    "",
    "> 全トークン（余白/角丸/影/タイポ含む実値）は get_tokens を呼ぶこと。",
  ].join("\n");
}

function formatSetup() {
  return [
    `# relay Design System — セットアップ（UI 作業の前に必ず確認）`,
    "",
    "relay のクラス（`.btn` / `.card` / `.input` 等）は **CSS 本体が読み込まれて初めて効く**。",
    "この MCP はクラス名・トークン等の「知識」を返すだけで CSS 実体は配らない。**CSS 未導入のまま relay クラスを書くとクラスが無効になり、ハードコードに逃げる結果になる**ので、まずここを満たすこと。",
    "",
    "## 1. インストール",
    "```bash",
    "npm install @light-right/design-system",
    "```",
    "",
    "## 2. CSS を読み込む（いずれか 1 つ）",
    "```js",
    "// ビルドツール（Vite / webpack 等）の JS / TS エントリから",
    'import "@light-right/design-system/css";',
    "```",
    "```css",
    "/* または Tailwind v4 のエントリ CSS で（プロジェクト側で Tailwind をビルドする場合） */",
    '@import "tailwindcss";',
    '@import "@light-right/design-system/tokens";',
    "```",
    "```html",
    "<!-- ビルドツールが無い素の HTML なら link でも可 -->",
    '<link rel="stylesheet" href="node_modules/@light-right/design-system/dist/relay.css" />',
    "```",
    "",
    "## 3. 導入確認",
    "- `node_modules/@light-right/design-system/dist/relay.css` が存在する",
    "- 上の import / link がアプリのエントリに書かれている",
    "- 確認: `.btn-primary` を置いてブランド緑のボタンが表示されれば効いている",
    "",
    "導入できたらまず **get_design_principles**（必須ルール・禁止パターン）と **list_components**（コンポーネント全体像）を読む。",
    "その後、使うコンポーネントごとに **get_component** を呼び、具体値が要るときだけ **get_tokens** を参照して UI を実装する。",
    "アイコンは `@light-right/design-system/icons`（SVG sprite）、ロゴ/イラストは list_assets を参照。",
  ].join("\n");
}

function formatAssets() {
  const assets = index.assets || [];
  const out = [`# relay Design System — ブランドアセット（${assets.length}）`, ""];
  if (!assets.length) {
    out.push("登録されたアセットがありません。");
    return out.join("\n");
  }
  out.push(
    "ロゴ・イラストの画像素材。URL は直リンク（GitHub raw・内容ハッシュ無しの固定URL）なので、",
    "そのまま `<img src=\"{URL}\">` や Markdown `![{用途}]({URL})` で埋め込める。relay 以外の独自ロゴ・イラストは使わないこと。",
    "",
    "| 名前 | 形式 | 用途 | URL |",
    "|---|---|---|---|",
  );
  for (const a of assets) {
    out.push(`| ${a.label || a.name} | ${a.format || ""} | ${a.alt || ""} | ${a.url} |`);
  }
  out.push("", "### 埋め込み用スニペット");
  for (const a of assets) {
    out.push(`- ${a.label || a.name}: \`![${a.alt || a.label || a.name}](${a.url})\``);
  }
  return out.join("\n");
}

function formatPrinciples() {
  return [
    "# relay Design System — 必須ルール & 禁止パターン",
    "",
    "AI が relay UI を生成する際、以下を必ず守ること。",
    "",
    formatBrandColors(),
    "",
    index.principles || "(principles 未取得)",
    "",
    index.forbiddenPatterns || "(forbidden patterns 未取得)",
  ].join("\n");
}

function runSearch(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return "検索クエリが空です。";

  const compHits = index.components
    .filter(
      (c) =>
        c.name.includes(q) ||
        (c.nameJa && c.nameJa.toLowerCase().includes(q)) ||
        (c.summary && c.summary.toLowerCase().includes(q)) ||
        (c.function && c.function.toLowerCase().includes(q)) ||
        (c.usage && [...(c.usage.ok || []), ...(c.usage.ng || [])].join(" ").toLowerCase().includes(q)) ||
        c.classes.some((cl) => cl.includes(q)) ||
        (c.doc && c.doc.toLowerCase().includes(q)),
    )
    .slice(0, 10);

  const tokenHits = [];
  for (const [cat, entries] of Object.entries(index.tokens)) {
    for (const t of entries) {
      if (t.name.toLowerCase().includes(q) || t.value.toLowerCase().includes(q)) {
        tokenHits.push({ cat, ...t });
      }
    }
  }

  const assetHits = (index.assets || []).filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      (a.label && a.label.toLowerCase().includes(q)) ||
      (a.alt && a.alt.toLowerCase().includes(q)),
  );

  const out = [`# 検索結果: "${query}"`, ""];
  if (compHits.length) {
    out.push("## コンポーネント（get_component で詳細）", "");
    for (const c of compHits) {
      out.push(`- **${c.name}**${c.nameJa ? `（${c.nameJa}）` : ""} → get_component("${c.name}")`);
    }
    out.push("");
  }
  if (tokenHits.length) {
    out.push(`## トークン（get_tokens でカテゴリ全件）`, "");
    for (const t of tokenHits.slice(0, 20)) out.push(`- [${t.cat}] \`${t.name}\`: ${t.value}`);
    if (tokenHits.length > 20) out.push(`- … 他 ${tokenHits.length - 20} 件`);
    out.push("");
  }
  if (assetHits.length) {
    out.push("## アセット（list_assets で全件・直リンク URL）", "");
    for (const a of assetHits) {
      out.push(`- **${a.label || a.name}**${a.format ? `（${a.format}）` : ""}: ${a.url}`);
    }
    out.push("");
  }
  if (!compHits.length && !tokenHits.length && !assetHits.length) {
    out.push("ヒットなし。list_components / get_tokens / get_design_principles を試してください。");
  }
  return out.join("\n");
}

/* --------------------------------------------------------------------- tools */

export const TOOLS = [
  {
    name: "get_setup",
    description:
      "【最初に必ず呼ぶ】relay の UI を実装する前に CSS 導入手順と確認方法を返す。relay のクラスは @light-right/design-system の CSS が読み込まれて初めて効くため、未導入だとどのコンポーネントも機能しない。UI 着手前のセットアップ確認に使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "list_components",
    description:
      "relay Design System の全コンポーネント一覧（英名 / 和名 / 概要 / 主要クラス）を返す。UI を組む前の全体把握に使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_component",
    description:
      "指定コンポーネントの完全仕様を返す。機能（用途・代替コンポーネントとの使い分け）と使用法（OK/NG パターン）を先頭に、続いて props・状態・色マッピング・usage 例・CSS クラス一覧・コピペ用 HTML スニペット・Figma リンク。name は 'button' / 'input' など（英名）。",
    inputSchema: {
      type: "object",
      properties: { name: { type: "string", description: "コンポーネント英名（例: button, input, alert, card）" } },
      required: ["name"],
      additionalProperties: false,
    },
  },
  {
    name: "get_tokens",
    description:
      "デザイントークンを返す。category 省略時は全カテゴリ。色・余白・タイポ・角丸・影をハードコードせずトークン経由で書くために使う。",
    inputSchema: {
      type: "object",
      properties: {
        category: { type: "string", enum: TOKEN_CATEGORIES, description: "トークンカテゴリ。省略で全件" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_design_principles",
    description:
      "relay の Non-Negotiable Principles（ハードコード禁止・semantic color・blessed spacing・typo セマンティック層・ARIA 状態 等）と禁止パターン Top 10 を返す。コード生成前のガードに使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "list_assets",
    description:
      "relay のブランドアセット（サービスロゴ・イラスト）一覧を直リンク URL 付きで返す。生成物にロゴやイラストを埋め込むときに使う（独自ロゴを作らない）。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "search",
    description:
      "コンポーネント / トークン / 規約を横断であいまい検索し、次に呼ぶべきツールを示す。例: 'ボタン', 'primary', '余白', 'shadow'。",
    inputSchema: {
      type: "object",
      properties: { query: { type: "string", description: "検索キーワード（日本語可）" } },
      required: ["query"],
      additionalProperties: false,
    },
  },
];

/**
 * Run a tool. Returns { text, isError? } — transports wrap this into their own
 * content envelope.
 */
export function callTool(name, args = {}) {
  switch (name) {
    case "get_setup":
      return { text: formatSetup() };
    case "list_components":
      return { text: formatComponentList() };
    case "get_component": {
      const c = findComponent(args.name);
      if (!c) {
        return {
          text: `コンポーネント "${args.name}" が見つかりません。\n利用可能: ${index.components
            .map((x) => x.name)
            .join(", ")}`,
        };
      }
      return { text: formatComponent(c) };
    }
    case "get_tokens": {
      if (args.category && !TOKEN_CATEGORIES.includes(args.category)) {
        return { text: `不明な category "${args.category}"。利用可能: ${TOKEN_CATEGORIES.join(", ")}` };
      }
      return { text: formatTokens(args.category) };
    }
    case "get_design_principles":
      return { text: formatPrinciples() };
    case "list_assets":
      return { text: formatAssets() };
    case "search":
      return { text: runSearch(args.query) };
    default:
      return { text: `Unknown tool: ${name}`, isError: true };
  }
}

/* ----------------------------------------------------------------- resources */

export function listResources() {
  return [
    {
      uri: "relay://design-constitution",
      name: "relay Design Constitution (DESIGN.md)",
      description: "思想・非交渉原則・クイックリファレンス・禁止パターンの 1 枚憲法",
      mimeType: "text/markdown",
    },
    ...index.components.map((c) => ({
      uri: `relay://component/${c.name}`,
      name: `Component: ${c.name}${c.nameJa ? `（${c.nameJa}）` : ""}`,
      description: c.summary || `relay ${c.name} component spec`,
      mimeType: "text/markdown",
    })),
  ];
}

/** Read a resource by uri → content object. Throws on unknown uri. */
export function readResource(uri) {
  if (uri === "relay://design-constitution") {
    return { uri, mimeType: "text/markdown", text: index.designConstitution };
  }
  const m = uri.match(/^relay:\/\/component\/(.+)$/);
  if (m) {
    const c = index.components.find((x) => x.name === m[1]);
    if (c) return { uri, mimeType: "text/markdown", text: formatComponent(c) };
  }
  throw new Error(`Unknown resource: ${uri}`);
}
