/**
 * relay Design System — MCP shared handlers (transport-agnostic).
 *
 *   The tool definitions, formatting, and dispatch logic live here so both
 *   transports reuse exactly the same behaviour:
 *     - src/mcp/server.mjs  → stdio (local, bundled to dist/mcp.mjs via esbuild)
 *     - src/mcp/worker.mjs  → Streamable HTTP on Cloudflare Workers (remote)
 *
 *   Data comes from dist/mcp-index.json (generated by scripts/build-mcp.mjs).
 *   Each transport's bundler (esbuild / wrangler) inlines this JSON import.
 *
 *   Tools:
 *     get_setup                — CSS 導入手順（UI 着手前に最初に呼ぶ）
 *     list_components          — every component with name / 和名 / summary / classes
 *     get_component(name)      — full spec: props, states, colors, usage, classes, snippet
 *     get_tokens(category?)    — colors / container / typography / spacing / radius / shadow
 *     get_design_principles    — non-negotiable rules + forbidden patterns
 *     get_accessibility        — WCAG 2.2 チェックリスト（DS 担保範囲 + プロダクト必須実装）
 *     list_assets              — brand assets (logo / illustrations) with直リンク URL
 *     search(query)            — fuzzy search across components / tokens / principles
 *
 *   sprint kit（planner/generator/evaluator + workflow の配布）は 2026-08 に解体済み。
 *   hardcode gate hook のみ get_setup の案内から単体導入する（正本: .claude/hooks/）。
 */

import index from "../../dist/mcp-index.json" with { type: "json" };

export { index };
export const SERVER_INFO = { name: "relay-design-system", version: index.version };
export const TOKEN_CATEGORIES = Object.keys(index.tokens); // colors, container, typography, spacing, radius, shadow

/**
 * Standing guidance returned in the `initialize` result. MCP clients load this
 * as system context at connect time, so — unlike a tool the agent must choose to
 * call — these rules stay in effect through a whole implementation session. This
 * targets the common failure mode where an agent connects, calls a tool once,
 * then drifts back to hardcoded values mid-build.
 */
export const INSTRUCTIONS = [
  "relay Design System の MCP。relay 系プロダクトの UI を作るときは必ずこのサーバーの情報を使い、自前のデザインや独自色で実装しないこと。",
  "",
  "【最初に必ず get_setup を呼ぶ】",
  "UI 作業を始める前に、まず get_setup を呼んで CSS の導入手順と確認方法を取得すること。",
  "relay のコンポーネントクラス（.btn / .card / .input 等）は npm パッケージ @light-right/design-system の CSS が読み込まれて初めて効く。MCP はクラス名やトークンの「知識」を渡すだけで CSS 実体は渡さない。CSS 未導入のまま relay クラスを書いても見た目が変わらず、ハードコードに逃げる結果になる。",
  "プロジェクトに未導入なら、UI を書く前に導入を済ませる（手順は get_setup 参照）。",
  "",
  "【実装フロー】",
  "0. get_setup を呼び、CSS が導入済みか確認する（未導入なら導入してから UI を書く）。",
  "1. get_design_principles で必須ルールと禁止パターンを、list_components でコンポーネントの全体像を把握する。",
  "2. 使うコンポーネントごとに get_component(\"<name>\") を呼び、返ってくるコピペ用 HTML スニペットとクラスを土台にする（自分で markup をゼロから組まない）。機能（用途）と使用法の NG を必ず確認し、用途が合わないコンポーネントを流用しない（例: 遷移に button を使わない）。",
  "3. 色・余白・タイポ・角丸・影の具体値が要るときは get_tokens を呼び、解決済みの実値またはトークン名を使う。",
  "4. ロゴ・イラストは list_assets の直リンク URL を使う（独自に作らない）。空状態・ヒーロー・案内・完了画面などイラストが場面に合うときは、独自の SVG イラストを描かず必ず list_assets から選ぶこと。",
  "5. アクセシビリティ: get_component の「アクセシビリティ」節（そのコンポーネントの実装必須対応）を必ず反映し、全体方針・WCAG 準拠は get_accessibility を参照する（aria-label / ラベル関連付け / role・aria-current 等を省略しない）。",
  "",
  "【事前知識で答えない】",
  "relay のクラス名・トークン値・コンポーネント仕様に関する回答は、UI を実装しない場合（質問への回答・コードレビュー・相談）でも、事前知識のみで答えず必ず get_component / get_tokens / search で確認してから答えること。仕様は更新されるため、記憶に頼ると古い・存在しないクラス（例: .badge-error — 正しくは .badge-solid-danger）を案内する恐れがある。",
  "「どのコンポーネントを使うべきか」の相談も、記憶で列挙せずまず list_components を呼ぶこと。",
  "",
  "【バージョンずれ】",
  `この MCP の知識は @light-right/design-system v${index.version} 基準。利用プロジェクトの導入バージョン（package.json）が異なる場合は node_modules 内の実 CSS（dist/relay.css）を正とし、「クラスを書いたのに効かない」ときはハードコードに逃げる前にバージョン差を疑うこと。`,
  "",
  "【ハード制約】",
  "- 色 / 余白 / タイポ / 角丸 / 影をハードコードしない（#hex やピクセル直書き・任意値クラスを避け、トークン／ユーティリティ経由で書く）。",
  "- 既存コンポーネントがある UI は手書きで再実装せず relay コンポーネントを使う。",
  "- 独自のブランド色（青など）を持ち込まない。基調はブランド緑 primary / 黄 secondary。",
].join("\n");

/* ------------------------------------------------------------------ helpers */

function findComponent(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return null;
  const byName = index.components.find((c) => c.name === q);
  if (byName) return byName;
  return (
    index.components.find((c) => c.name.includes(q) || q.includes(c.name)) ||
    index.components.find((c) => c.nameJa && c.nameJa.toLowerCase() === q) ||
    index.components.find((c) => c.classes.includes(q)) ||
    null
  );
}

function formatComponentList() {
  const lines = [
    `# relay Design System — ${index.components.length} components (v${index.version})`,
    "",
    `各コンポーネントの完全仕様は get_component("<name>") を呼んでください（props / 状態 / 色 / usage / クラス / snippet）。`,
    `UI を書く前に get_design_principles で必須ルールと禁止パターンを確認することを推奨します。`,
    "",
  ];
  for (const c of index.components) {
    const ja = c.nameJa ? `（${c.nameJa}）` : "";
    // 機能の 1 行目があればそれを概要に使う（用途が伝わる）。無ければ従来の summary。
    const lead = c.function ? c.function.split("\n")[0].trim() : c.summary;
    const summary = lead ? ` — ${lead}` : "";
    const cls = c.classes.slice(0, 6).join(", ");
    lines.push(`- **${c.name}**${ja}${summary}`);
    lines.push(`  classes: ${cls}${c.classes.length > 6 ? ", …" : ""}`);
  }
  return lines.join("\n");
}

/** Remove the column-0 `<label>:` lines and their indented bodies from a header doc. */
function stripDocLabels(doc, labels) {
  const out = [];
  let skipping = false;
  for (const line of doc.split("\n")) {
    const trimmed = line.trim();
    if (labels.some((l) => trimmed === `${l}:`)) { skipping = true; continue; }
    if (skipping) {
      if (trimmed === "") continue; // blank line inside/after the block
      if (/^\s/.test(line)) continue; // indented body → still in the block
      skipping = false; // hit the next column-0 label → block ended
    }
    out.push(line);
  }
  return out.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

function formatComponent(c) {
  const ja = c.nameJa ? ` （${c.nameJa}）` : "";
  const out = [`# ${c.name}${ja}`];
  out.push("");
  // 基準バージョンと、ずれていた場合の正の在り処を毎回明示する（利用プロジェクトの
  // 導入バージョンが古い/新しい場合、この知識にあるクラスが実 CSS に無いことがある）。
  out.push(
    `> この仕様は @light-right/design-system **v${index.version}** 基準。利用プロジェクトの導入バージョン（package.json で確認）が異なる場合は、node_modules 内の実 CSS（dist/relay.css）を正とすること。`,
    "",
  );

  // 機能 / 使用法 を最初に出す（クラスや snippet を掴む前に「用途と NG」を読ませる）。
  if (c.function) out.push("## 機能", "", c.function, "");
  if (c.usage && ((c.usage.ok && c.usage.ok.length) || (c.usage.ng && c.usage.ng.length))) {
    out.push("## 使用法", "");
    for (const ok of c.usage.ok || []) out.push(`- ✅ ${ok}`);
    for (const ng of c.usage.ng || []) out.push(`- ❌ ${ng}`);
    out.push("");
  }
  if (c.accessibility && c.accessibility.length) {
    out.push("## アクセシビリティ（実装時の必須対応）", "");
    for (const a of c.accessibility) out.push(`- ${a}`);
    out.push("", "> WCAG 2.2 の全体チェックリスト（DS 担保範囲・プロダクト必須実装）は get_accessibility を参照（topic で節指定可）。", "");
  }

  // 仕様（doc）からは 機能/使用法/アクセシビリティ ブロックを除いて重複表示を避ける（doc 全文は index に保持）。
  const spec = c.doc ? stripDocLabels(c.doc, ["機能", "使用法", "アクセシビリティ"]) : "";
  out.push(`## 仕様（src/components/${c.name}.css ヘッダより）`, "", spec || "（ドキュメントコメントなし）", "");
  out.push(`## CSS クラス（${c.classes.length}）`, "", c.classes.map((x) => `.${x}`).join(", "), "");
  out.push("## コピペ用 HTML スニペット", "");
  out.push(c.snippet ? "```html\n" + c.snippet + "\n```" : "（このコンポーネントの snippet はありません。上記の Usage と CSS クラスを参照）");
  return out.join("\n");
}

function formatTokens(category) {
  const cats = category ? [category] : TOKEN_CATEGORIES;
  const out = [`# relay Design System — design tokens (v${index.version})`, ""];
  out.push(
    "値は解決済みの実値（例: --color-primary-500 = #30b686）。CSS が無い環境（スタンドアロン生成）でも、この実値をそのまま使うこと。",
    "Tailwind ユーティリティ名は --color-x-500 → bg-x-500、--spacing*N → p-N 等に対応。",
    "",
  );
  for (const cat of cats) {
    const entries = index.tokens[cat];
    if (!entries) continue;
    out.push(`## ${cat} (${entries.length})`, "");
    for (const t of entries) out.push(`- \`${t.name}\`: ${t.value}${t.via ? ` (= ${t.via})` : ""}`);
    out.push("");
  }
  return out.join("\n");
}

/** Resolved value of a color token by name (e.g. "--color-primary-500" → "#30b686"). */
function colorValue(name) {
  const t = (index.tokens.colors || []).find((c) => c.name === name);
  return t ? t.value : "?";
}

function formatBrandColors() {
  return [
    "## ブランド基調色（実値・これを使う）",
    "",
    "relay の CSS を読み込まない環境（claude.ai 等のスタンドアロン生成）では、下記の実値を直接使うこと。**青などの独自色は使わない。**",
    "",
    `- primary（ブランド緑）: \`bg-primary-500\` = ${colorValue("--color-primary-500")} / hover \`bg-primary-600\` = ${colorValue("--color-primary-600")} / 濃 \`primary-700\` = ${colorValue("--color-primary-700")}`,
    `- secondary（ブランド黄）: \`secondary-500\` = ${colorValue("--color-secondary-500")}`,
    `- 本文テキスト: \`text-fg-high\` = ${colorValue("--color-fg-high")} / \`text-fg-middle\` = ${colorValue("--color-fg-middle")} / \`text-fg-low\` = ${colorValue("--color-fg-low")}`,
    `- ステータス: success ${colorValue("--color-success-500")} / warning ${colorValue("--color-warning-500")} / negative ${colorValue("--color-negative-500")} / info ${colorValue("--color-info-500")}`,
    `- 背景/境界: page ${colorValue("--color-page")} / border \`stroke-middle\` ${colorValue("--color-stroke-middle")}`,
    "",
    "> 全トークン（余白/角丸/影/タイポ含む実値）は get_tokens を呼ぶこと。",
  ].join("\n");
}

function formatSetup() {
  return [
    `# relay Design System — セットアップ（UI 作業の前に必ず確認）`,
    "",
    "relay のクラス（`.btn` / `.card` / `.input` 等）は **CSS 本体が読み込まれて初めて効く**。",
    "この MCP はクラス名・トークン等の「知識」を返すだけで CSS 実体は配らない。**CSS 未導入のまま relay クラスを書くとクラスが無効になり、ハードコードに逃げる結果になる**ので、まずここを満たすこと。",
    "",
    "## 1. インストール",
    "```bash",
    "npm install @light-right/design-system",
    "```",
    "",
    "## 2. CSS を読み込む（いずれか 1 つ）",
    "```js",
    "// ビルドツール（Vite / webpack 等）の JS / TS エントリから",
    'import "@light-right/design-system/css";',
    "```",
    "```css",
    "/* または Tailwind v4 のエントリ CSS で（プロジェクト側で Tailwind をビルドする場合） */",
    '@import "tailwindcss";',
    '@import "@light-right/design-system/tokens";',
    "```",
    "```html",
    "<!-- ビルドツールが無い素の HTML なら link でも可 -->",
    '<link rel="stylesheet" href="node_modules/@light-right/design-system/dist/relay.css" />',
    "```",
    "",
    "## 3. 導入確認",
    "- `node_modules/@light-right/design-system/dist/relay.css` が存在する",
    "- 上の import / link がアプリのエントリに書かれている",
    "- 確認: `.btn-primary` を置いてブランド緑のボタンが表示されれば効いている",
    "",
    "## 4. バージョン確認（導入済みプロジェクトの場合）",
    `- この MCP の知識は **v${index.version}** 基準。利用プロジェクトの package.json / lock の \`@light-right/design-system\` のバージョンを確認すること`,
    "- バージョンが異なる場合、この MCP が案内するクラスが実 CSS に存在しない（またはその逆の）可能性がある。**node_modules 内の実 CSS（dist/relay.css）を正**とし、更新が必要ならユーザーに `npm update @light-right/design-system` を提案する",
    "",
    "## 5. （推奨・Claude Code のみ）ハードコード検知 hook の導入",
    "relay には「Write/Edit の直後にハードコード違反（生 hex 色・font-size 生値・祝福外 spacing・独自状態クラス・外部スプライト参照等）を検知し、Claude に即フィードバックして修正させる」PostToolUse hook がある。導入すると違反が成果物に混入する前に書き込み時点で弾かれる。**ユーザーに導入するか確認の上**、次の 2 手順で有効化する（Node.js 必須）:",
    "",
    "```bash",
    "# 1. hook 本体を取得（正本: relay-design-system リポジトリ）",
    "mkdir -p .claude/hooks && curl -fsSL \\",
    "  https://raw.githubusercontent.com/relay-development/relay-design-system/main/.claude/hooks/relay-hardcode-gate.mjs \\",
    "  -o .claude/hooks/relay-hardcode-gate.mjs",
    "```",
    "",
    "```json",
    "// 2. .claude/settings.json にマージ（既存の hooks キーがあれば PostToolUse 配列に追記）",
    "{",
    '  "hooks": {',
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Write|Edit",',
    '        "hooks": [{ "type": "command", "command": "node .claude/hooks/relay-hardcode-gate.mjs" }]',
    "      }",
    "    ]",
    "  }",
    "}",
    "```",
    "",
    "- 正当な例外（第三者ブランド色）は同一行コメントに「ブランド」/ brand と書けばスキップされる",
    "- hook が認識されないときは Claude Code のセッションを再起動する。claude.ai 等 hooks の無い環境ではこの手順は不要（スキップしてよい）",
    "",
    "## 6. レイアウト・間隔は標準 Tailwind ユーティリティで組む",
    "relay.css には標準ユーティリティ（`flex` / `grid` / `gap-*` / `p-*` / `m-*` / `w-*` / `h-*` / `text-{left,center,right}` / `overflow-*` / `sr-only` 等 ＋ `sm:` `md:` `lg:` `focus:` 変種）と、役割ベースのセマンティック色（`text-fg-{high,middle,low}` / `bg-surface` / `border-stroke-*` / `bg-primary-600` 等）が **safelist 済みで常に含まれる**。import 済みの relay.css に実在するので、**実 CSS ファイルを grep して存在確認する必要はない**。特定のクラスが使えるか確かめたいときだけ `search(\"クラス名\")` を呼ぶ（実在すれば「存在します」、無ければ「存在しません」と明言して返る）。複数まとめて確かめるなら空白区切りで 1 回に渡す（例: `search(\"flex-1 md:grid-cols-3 tabular-nums\")` → 件ごとの ○×表）。",
    "- relay.css は 1 行にミニファイされている。grep しても全文が返るだけで存在確認には使えないので、確認は必ず search で行う。",
    "- 任意値（`p-[13px]` 等）・生 hex 色は従来どおり不可 → トークン／ユーティリティ経由で書く（ハードコード hook が弾く）。",
    "",
    "導入できたらまず **get_design_principles**（必須ルール・禁止パターン）と **list_components**（コンポーネント全体像）を読む。",
    "その後、使うコンポーネントごとに **get_component** を呼び、具体値が要るときだけ **get_tokens** を参照して UI を実装する。",
    "アイコンは `@light-right/design-system/icons`（SVG sprite）、ロゴ/イラストは list_assets を参照。",
  ].join("\n");
}

function formatAssets() {
  const assets = index.assets || [];
  const out = [`# relay Design System — ブランドアセット（${assets.length}）`, ""];
  if (!assets.length) {
    out.push("登録されたアセットがありません。");
    return out.join("\n");
  }
  out.push(
    "ロゴ・イラストの画像素材。URL は直リンク（GitHub raw・内容ハッシュ無しの固定URL）なので、",
    "そのまま `<img src=\"{URL}\">` や Markdown `![{用途}]({URL})` で埋め込める。relay 以外の独自ロゴ・イラストは使わないこと。",
    "空状態・ヒーロー・案内・完了画面などイラストが合う場面では、独自の SVG イラストを描かずここから選ぶ（1 点で十分。alt は下表の用途を使う）。",
    "",
    "| 名前 | 形式 | 用途 | URL |",
    "|---|---|---|---|",
  );
  for (const a of assets) {
    out.push(`| ${a.label || a.name} | ${a.format || ""} | ${a.alt || ""} | ${a.url} |`);
  }
  out.push("", "### 埋め込み用スニペット");
  for (const a of assets) {
    out.push(`- ${a.label || a.name}: \`![${a.alt || a.label || a.name}](${a.url})\``);
  }
  return out.join("\n");
}

function formatPrinciples() {
  return [
    "# relay Design System — デザイン原則・必須ルール & 禁止パターン",
    "",
    "AI が relay UI を生成する際、以下を必ず守ること。",
    "",
    index.designPhilosophy || "(design principles 未取得)",
    "",
    formatBrandColors(),
    "",
    index.principles || "(principles 未取得)",
    "",
    index.forbiddenPatterns || "(forbidden patterns 未取得)",
  ].join("\n");
}

/**
 * docs/ACCESSIBILITY.md を「## グループ」「### 節」の 2 階層セクションに分割する。
 * ## 直下の本文（担保早見表など ### を持たない章）も topic で引けるよう、
 * グループ自身も直下本文つきのセクションとして持つ。
 */
function splitA11ySections(full) {
  const sections = [];
  let group = null;
  let current = null;
  for (const line of full.split("\n")) {
    if (/^## /.test(line)) {
      if (current) sections.push(current);
      group = line.replace(/^## /, "").trim();
      current = { level: 2, group, heading: group, body: [] };
      continue;
    }
    if (/^### /.test(line)) {
      if (current) sections.push(current);
      current = { level: 3, group, heading: line.replace(/^### /, "").trim(), body: [] };
      continue;
    }
    if (current) current.body.push(line);
  }
  if (current) sections.push(current);
  return sections;
}

function a11yToc(sections) {
  const out = [];
  for (const s of sections) {
    if (s.level === 2) out.push(`- **${s.heading}**`);
    else out.push(`  - ${s.heading}`);
  }
  return out;
}

/**
 * WCAG 2.2 (A/AA/AAA) チェックリスト。topic 未指定なら要約（DS 担保範囲／プロダクト
 * 必須実装）と節目次を返し、topic 指定で該当節の本文だけを返す 2 段構え。
 * 以前は全文 31K 字を一括で返しており、実測（evals の行動ログ）で 1 回の応答が
 * 全ツール応答合計の約半分を占めていたため、必要な節に絞って取得する形に変更した。
 * コンポーネント個別の必須対応は get_component の「アクセシビリティ」節を参照。
 */
function formatAccessibility(topic) {
  const a = index.accessibility;
  if (!a) {
    return "アクセシビリティのチェックリスト（docs/ACCESSIBILITY.md）が index に見つかりません。カタログの『アクセシビリティ』ページを参照してください。";
  }
  const header = ["# relay Design System — アクセシビリティ（WCAG 2.2 実務チェックリスト）", ""];
  if (!a.full) {
    // 旧 index（全文なし）: 要約だけ返す
    const out = [...header];
    if (a.provides) out.push(a.provides, "");
    if (a.productMust) out.push(a.productMust, "");
    return out.join("\n");
  }
  const sections = splitA11ySections(a.full);

  if (topic) {
    const q = String(topic).toLowerCase();
    let hits = sections.filter((s) => s.heading.toLowerCase().includes(q));
    let via = "見出し一致";
    if (!hits.length) {
      hits = sections.filter((s) => s.body.join("\n").toLowerCase().includes(q));
      via = "本文一致";
    }
    if (!hits.length) {
      return [
        ...header,
        `topic "${topic}" に一致する節がありません。以下の目次から選び直してください:`,
        "",
        ...a11yToc(sections),
      ].join("\n");
    }
    const MAX = 5;
    const out = [
      ...header,
      `## topic "${topic}" の該当節（${via} ${hits.length} 件${hits.length > MAX ? `・先頭 ${MAX} 件を表示。絞り込むには topic をより具体的に` : ""}）`,
      "",
    ];
    for (const s of hits.slice(0, MAX)) {
      out.push(`### ${s.heading}${s.level === 3 ? `（${s.group}）` : ""}`);
      if (s.level === 2) {
        // グループ一致は直下本文 + 所属節の見出し一覧（全節の本文は返さない）
        out.push(...s.body);
        const children = sections.filter((c) => c.level === 3 && c.group === s.heading);
        if (children.length) {
          out.push("", "所属する節（topic で個別指定して本文を取得）:", ...children.map((c) => `- ${c.heading}`));
        }
      } else {
        out.push(...s.body);
      }
      out.push("");
    }
    out.push("> コンポーネント個別の必須対応は get_component の「アクセシビリティ」節を参照。");
    return out.join("\n");
  }

  const out = [
    ...header,
    "relay を採用したプロダクトが WCAG 2.2（A / AA / AAA）に準拠するための、DS 担保範囲とプロダクト側責務のチェックリスト。" +
      '節の本文は topic（見出しの部分一致。例: "2.4.1" / "スキップ" / "タイムアウト"）を指定して取得すること。' +
      'コンポーネント個別の必須対応は get_component("<name>") の「アクセシビリティ」節を参照。',
    "",
  ];
  if (a.provides) out.push(a.provides, "");
  if (a.productMust) out.push(a.productMust, "");
  out.push("---", "", "## 節目次（本文は topic で指定して取得）", "", ...a11yToc(sections));
  return out.join("\n");
}

function runSearch(query) {
  const q = String(query || "").trim().toLowerCase();
  if (!q) return "検索クエリが空です。";

  const compHits = index.components
    .filter(
      (c) =>
        c.name.includes(q) ||
        (c.nameJa && c.nameJa.toLowerCase().includes(q)) ||
        (c.summary && c.summary.toLowerCase().includes(q)) ||
        (c.function && c.function.toLowerCase().includes(q)) ||
        (c.usage && [...(c.usage.ok || []), ...(c.usage.ng || [])].join(" ").toLowerCase().includes(q)) ||
        c.classes.some((cl) => cl.includes(q)) ||
        (c.doc && c.doc.toLowerCase().includes(q)),
    )
    .slice(0, 10);

  const tokenHits = [];
  for (const [cat, entries] of Object.entries(index.tokens)) {
    for (const t of entries) {
      if (t.name.toLowerCase().includes(q) || t.value.toLowerCase().includes(q)) {
        tokenHits.push({ cat, ...t });
      }
    }
  }

  const assetHits = (index.assets || []).filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      (a.label && a.label.toLowerCase().includes(q)) ||
      (a.alt && a.alt.toLowerCase().includes(q)),
  );

  // クラス存在チェック — 「このクラスは relay.css に実在し効くか」に答え、実 CSS を grep させない。
  // クラス名は大小・記号を保つため元のクエリで照合する（Tailwind は小文字）。
  // 空白・カンマ区切りで複数渡されたら一括判定（確認したいクラスが多いと AI は grep に流れるため、
  // 1 回の呼び出しで全件に答える。実例: 30 個超の存在確認を grep ループで試み 7 回失敗した）。
  const all = index.allClasses || [];
  const isClassShaped = (t) => /^[a-z0-9][a-z0-9:_\-\/.%!\[\]()#]*$/i.test(t);
  const tokens = String(query || "")
    .split(/[\s,]+/)
    .map((t) => t.trim().replace(/^\./, ""))
    .filter(Boolean);
  // 英単語 2 語のあいまい検索（"external link" 等）を誤って一括判定に回さないよう、
  // 「実在クラス」か「Tailwind らしい記号（- / :）を含む」トークンが 2 つ以上あるときだけ一括判定にする。
  // 旧条件（全トークンが該当）は、存在しない素の語（underline / block / ol 等）が 1 つ混ざるだけで
  // 一括判定から外れ「ヒットなし」に落ちていた（evals 2026-09-03: 10 お題で 13 回の投げ直し）。
  const classLike = (t) => all.includes(t) || /[-:]/.test(t);
  const bulkClassMode =
    tokens.length >= 2 && tokens.every(isClassShaped) && tokens.filter(classLike).length >= 2;
  const rawQ = tokens.length === 1 ? tokens[0] : "";
  const classExact = !!rawQ && all.includes(rawQ);
  const classPrefix = !classExact && rawQ.length >= 2 ? all.filter((c) => c.startsWith(rawQ)).slice(0, 15) : [];
  // クラス形（ASCII・記号のみ）で見つからなければ「存在しない」と明言する。
  // 「ヒットなし」だけだと AI は search の否定を信用せず実 CSS を grep しに行く（実例: tabular-nums）。
  const classMissing = !!rawQ && !classExact && isClassShaped(rawQ) && (/[-:]/.test(rawQ) || !compHits.length && !tokenHits.length && !assetHits.length);

  if (bulkClassMode) {
    const rows = tokens.map((t) => {
      if (all.includes(t)) return `| \`${t}\` | ✅ 存在 | |`;
      const cand = all.filter((c) => c.startsWith(t)).slice(0, 5);
      return `| \`${t}\` | ❌ なし | ${cand.length ? cand.map((c) => `\`${c}\``).join(" ") : ""} |`;
    });
    const missing = tokens.filter((t) => !all.includes(t));
    return [
      `# クラス存在チェック（${tokens.length} 件）`,
      "",
      "| クラス | relay.css | 前方一致の実在候補 |",
      "|---|---|---|",
      ...rows,
      "",
      missing.length
        ? `❌ の ${missing.length} 件は relay.css に含まれず、書いても効かない。候補列から選ぶか、別のユーティリティ／コンポーネントで組み替える。`
        : "全件 relay.css に存在する。そのまま使える。",
      "この結果が正本なので、実 CSS ファイルを grep して再確認する必要はない。",
    ].join("\n");
  }

  const out = [`# 検索結果: "${query}"`, ""];
  if (classExact) {
    out.push(`## クラス \`${rawQ}\` は relay.css に存在します（そのまま使えます・実 CSS の grep 不要）`, "");
  }
  if (classMissing) {
    out.push(
      `## クラス \`${rawQ}\` は relay.css に存在しません（safelist 外。書いても効かない・実 CSS を grep しても見つからない）`,
      "",
      classPrefix.length
        ? "下の前方一致候補から選ぶか、別のユーティリティ／コンポーネントで組み替えてください。"
        : "別のユーティリティ／コンポーネントで組み替えてください（複数クラスの一括確認は空白区切りで search に渡せます）。",
      "",
    );
  }
  if (classPrefix.length) {
    out.push(`## \`${rawQ}…\` で始まる実在クラス（relay.css に含まれる）`, "", ...classPrefix.map((c) => `- \`${c}\``), "");
  }
  if (compHits.length) {
    out.push("## コンポーネント（get_component で詳細）", "");
    for (const c of compHits) {
      out.push(`- **${c.name}**${c.nameJa ? `（${c.nameJa}）` : ""} → get_component("${c.name}")`);
    }
    out.push("");
  }
  if (tokenHits.length) {
    out.push(`## トークン（get_tokens でカテゴリ全件）`, "");
    for (const t of tokenHits.slice(0, 20)) out.push(`- [${t.cat}] \`${t.name}\`: ${t.value}`);
    if (tokenHits.length > 20) out.push(`- … 他 ${tokenHits.length - 20} 件`);
    out.push("");
  }
  if (assetHits.length) {
    out.push("## アセット（list_assets で全件・直リンク URL）", "");
    for (const a of assetHits) {
      out.push(`- **${a.label || a.name}**${a.format ? `（${a.format}）` : ""}: ${a.url}`);
    }
    out.push("");
  }
  if (!compHits.length && !tokenHits.length && !assetHits.length && !classExact && !classPrefix.length && !classMissing) {
    // 誘導先は「どのツールに何があるか」を添える。a11y・ユーティリティは search の索引外なので
    // get_accessibility への誘導が必須（実例: 「スキップリンク sr-only」の検索が空振りし、
    // エージェントが誘導に頼らず自力で get_accessibility に到達して正解を得た）
    out.push(
      "ヒットなし。探しものに応じて: コンポーネント一覧は list_components、トークン実値は get_tokens、" +
        "設計原則・禁止パターンは get_design_principles、アクセシビリティやユーティリティ" +
        "（sr-only / スキップリンク / フォーカスリング等）の実装ガイドは get_accessibility（topic で節指定可）を参照してください。",
    );
  }
  return out.join("\n");
}

/* --------------------------------------------------------------------- tools */

export const TOOLS = [
  {
    name: "get_setup",
    description:
      "【最初に必ず呼ぶ】relay の UI を実装する前に CSS 導入手順と確認方法を返す。relay のクラスは @light-right/design-system の CSS が読み込まれて初めて効くため、未導入だとどのコンポーネントも機能しない。UI 着手前のセットアップ確認に使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "list_components",
    description:
      "relay Design System の全コンポーネント一覧（英名 / 和名 / 概要 / 主要クラス）を返す。UI を組む前の全体把握に使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_component",
    description:
      "指定コンポーネントの完全仕様を返す。機能（用途・代替コンポーネントとの使い分け）・使用法（OK/NG パターン）・アクセシビリティ（実装時の必須対応）を先頭に、続いて props・状態・色マッピング・usage 例・CSS クラス一覧・コピペ用 HTML スニペット。name は 'button' / 'input' など（英名）。",
    inputSchema: {
      type: "object",
      properties: { name: { type: "string", description: "コンポーネント英名（例: button, input, alert, card）" } },
      required: ["name"],
      additionalProperties: false,
    },
  },
  {
    name: "get_tokens",
    description:
      "デザイントークンを返す。category 省略時は全カテゴリ。色・余白・タイポ・角丸・影をハードコードせずトークン経由で書くために使う。",
    inputSchema: {
      type: "object",
      properties: {
        category: { type: "string", enum: TOKEN_CATEGORIES, description: "トークンカテゴリ。省略で全件" },
      },
      additionalProperties: false,
    },
  },
  {
    name: "get_design_principles",
    description:
      "relay のデザイン原則（ゆったりとした余白・わかりやすい表現・明瞭な色使い）、Non-Negotiable Principles（ハードコード禁止・semantic color・blessed spacing・typo セマンティック層・ARIA 状態 等）、禁止パターン要約を返す。コード生成前のガードに使う。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_accessibility",
    description:
      "relay のアクセシビリティ実務チェックリスト（WCAG 2.2 A/AA/AAA）。topic 未指定なら DS 担保範囲・プロダクト必須実装の要約と節目次を返す。実装知識（スキップリンク・フォーカス・タイムアウト等）が必要なときは目次から topic を指定して該当節の本文を取得する。コンポーネント個別の必須対応は get_component の「アクセシビリティ」節を参照。",
    inputSchema: {
      type: "object",
      properties: {
        topic: {
          type: "string",
          description:
            '節の絞り込みキーワード。見出しの部分一致（なければ本文の全文検索）。例: "2.4.1" / "スキップ" / "フォーカス" / "タイムアウト"。未指定なら要約 + 節目次',
        },
      },
      additionalProperties: false,
    },
  },
  {
    name: "list_assets",
    description:
      "relay のブランドアセット（サービスロゴ・イラスト）一覧を直リンク URL 付きで返す。空状態・ヒーロー・案内・完了画面などイラストが合う場面では、独自の SVG イラストを描かずここから選ぶこと（独自ロゴ・独自イラストは禁止）。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "search",
    description:
      "コンポーネント / トークン / 規約を横断であいまい検索し、次に呼ぶべきツールを示す。例: 'ボタン', 'primary', '余白', 'shadow'。クラス名を渡すと relay.css に存在するか／しないかを明言して返す（実 CSS の grep 不要）。空白区切りで複数渡せば一括で ○× 表になる（例: 'flex-1 md:grid-cols-3 tabular-nums'）。",
    inputSchema: {
      type: "object",
      properties: { query: { type: "string", description: "検索キーワード（日本語可）" } },
      required: ["query"],
      additionalProperties: false,
    },
  },
];

/**
 * Run a tool. Returns { text, isError? } — transports wrap this into their own
 * content envelope.
 */
export function callTool(name, args = {}) {
  switch (name) {
    case "get_setup":
      return { text: formatSetup() };
    case "list_components":
      return { text: formatComponentList() };
    case "get_component": {
      const c = findComponent(args.name);
      if (!c) {
        return {
          text: `コンポーネント "${args.name}" が見つかりません。\n利用可能: ${index.components
            .map((x) => x.name)
            .join(", ")}`,
        };
      }
      return { text: formatComponent(c) };
    }
    case "get_tokens": {
      if (args.category && !TOKEN_CATEGORIES.includes(args.category)) {
        return { text: `不明な category "${args.category}"。利用可能: ${TOKEN_CATEGORIES.join(", ")}` };
      }
      return { text: formatTokens(args.category) };
    }
    case "get_design_principles":
      return { text: formatPrinciples() };
    case "get_accessibility":
      return { text: formatAccessibility(args.topic) };
    case "list_assets":
      return { text: formatAssets() };
    case "search":
      return { text: runSearch(args.query) };
    default:
      return { text: `Unknown tool: ${name}`, isError: true };
  }
}

/* ----------------------------------------------------------------- resources */

export function listResources() {
  return [
    {
      uri: "relay://design-constitution",
      name: "relay Design Constitution (DESIGN.md)",
      description: "思想・非交渉原則・クイックリファレンス・禁止パターンの 1 枚憲法",
      mimeType: "text/markdown",
    },
    ...index.components.map((c) => ({
      uri: `relay://component/${c.name}`,
      name: `Component: ${c.name}${c.nameJa ? `（${c.nameJa}）` : ""}`,
      description: c.summary || `relay ${c.name} component spec`,
      mimeType: "text/markdown",
    })),
  ];
}

/** Read a resource by uri → content object. Throws on unknown uri. */
export function readResource(uri) {
  if (uri === "relay://design-constitution") {
    return { uri, mimeType: "text/markdown", text: index.designConstitution };
  }
  const m = uri.match(/^relay:\/\/component\/(.+)$/);
  if (m) {
    const c = index.components.find((x) => x.name === m[1]);
    if (c) return { uri, mimeType: "text/markdown", text: formatComponent(c) };
  }
  throw new Error(`Unknown resource: ${uri}`);
}

/* ------------------------------------------------------------------- prompts */

/**
 * MCP prompts. sprint kit の解体（2026-08）に伴い空。
 * トランスポート（stdio / Worker）との API 互換のため定義自体は残す。
 */
export const PROMPTS = [];

/** Build a prompt's messages. Throws on unknown prompt name. */
export function getPrompt(name) {
  throw new Error(`Unknown prompt: ${name}`);
}
