/**
 * Build an SVG sprite from a curated subset of Lucide icons.
 *
 *   input:  node_modules/lucide-static/icons/{name}.svg
 *   output: dist/icons.svg
 *
 *   Each Lucide source SVG is wrapped in a <symbol id="lucide-{name}">,
 *   preserving its stroke / fill / viewBox attributes so a bare
 *     <svg class="icon icon-md"><use href="…#lucide-search" /></svg>
 *   renders correctly without extra CSS.
 *
 *   Add more icons by appending to the ICONS list and re-running.
 */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");

export const ICONS = [
  // Status / Feedback
  "info", "check-circle", "alert-triangle", "alert-circle", "x-circle",
  // Action
  "plus", "minus", "x", "check", "pencil", "trash-2", "copy", "download",
  "upload", "refresh-cw", "send",
  // Navigation
  "chevron-up", "chevron-down", "chevron-left", "chevron-right",
  "chevrons-up-down", "arrow-left", "menu", "more-horizontal", "more-vertical",
  "home",
  // Object
  "file", "files", "folder", "folder-cog", "link", "external-link", "image",
  // User
  "user", "users", "smile", "shield-check", "medal", "settings", "help-circle",
  "log-in", "log-out",
  // Search / Filter
  "search", "filter", "hash",
  // Visibility
  "eye", "eye-off", "lock",
  // Time / Date
  "calendar", "clock",
  // Communication
  "mail", "bell",
];

const SOURCE_DIR = path.join(projectRoot, "node_modules", "lucide-static", "icons");
// Sprite is written to two locations:
//   - dist/icons.svg  → shipped via npm `exports./icons` for consumers
//   - examples/icons.svg → served by the dev server / GitHub Pages preview site
//                          so the catalog itself can <use href="./icons.svg#…">
const OUT_PATHS = [
  path.join(projectRoot, "dist", "icons.svg"),
  path.join(projectRoot, "examples", "icons.svg"),
];

// Attributes we copy from each Lucide source <svg> onto the resulting <symbol>.
// width / height / class / xmlns are dropped because the rendered <svg class="icon"> handles sizing.
const KEEP_ATTRS = new Set([
  "viewBox", "fill", "stroke",
  "stroke-width", "stroke-linecap", "stroke-linejoin",
]);

function extractSvgAttrs(svgOpenTag) {
  const attrs = {};
  for (const m of svgOpenTag.matchAll(/(\S+?)\s*=\s*"([^"]*)"/g)) {
    if (KEEP_ATTRS.has(m[1])) attrs[m[1]] = m[2];
  }
  return attrs;
}

function attrsToString(attrs) {
  return Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ");
}

async function convertOne(name) {
  const filePath = path.join(SOURCE_DIR, `${name}.svg`);
  if (!existsSync(filePath)) {
    throw new Error(`Icon "${name}" not found at ${filePath}. Is the name correct in the ICONS list?`);
  }
  const raw = await readFile(filePath, "utf8");

  const openMatch = raw.match(/<svg\b[^>]*>/);
  if (!openMatch) throw new Error(`No <svg> open tag in ${filePath}`);
  const attrs = extractSvgAttrs(openMatch[0]);

  // Strip comments + the original <svg> wrapper, keep inner content.
  const inner = raw
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<svg\b[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim()
    .split("\n")
    .map((line) => "    " + line.trim())
    .filter((line) => line.trim().length > 0)
    .join("\n");

  return `  <symbol id="lucide-${name}" ${attrsToString(attrs)}>\n${inner}\n  </symbol>`;
}

async function main() {
  console.log(`Building Lucide sprite (${ICONS.length} icons)…`);

  const symbols = await Promise.all(ICONS.map(convertOne));

  const out = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!-- Generated by scripts/build-icons.mjs. Source: lucide-static (ISC). -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">`,
    `  <defs>`,
    ...symbols,
    `  </defs>`,
    `</svg>`,
    ``,
  ].join("\n");

  const sizeKb = (Buffer.byteLength(out, "utf8") / 1024).toFixed(1);
  for (const p of OUT_PATHS) {
    await mkdir(path.dirname(p), { recursive: true });
    await writeFile(p, out, "utf8");
    console.log(`✓ Wrote ${path.relative(projectRoot, p)} (${sizeKb} KB, ${ICONS.length} icons)`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
